<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="portfolio">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="firstname" type="xs:string"/>
                            <xs:element name="lastname" type="xs:string"/>
                            <xs:element name="course" type="xs:string"/>
                            <xs:element name="year" type="xs:string"/>
                            <xs:element name="age" type="xs:integer"/>
                            <xs:element name="address" type="xs:string"/>
                            <xs:element name="skills">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="skill" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="education" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="item" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="awards" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="award" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
