<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="student">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="info">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="first_name" type="xs:string" minOccurs="1"/>
                            <xs:element name="middle_name" type="xs:string" minOccurs="0"/>
                            <xs:element name="last_name" type="xs:string" minOccurs="1"/>
                            <xs:element name="age" type="xs:integer" minOccurs="1"/>
                            <xs:element name="year" type="xs:string" minOccurs="1"/>
                            <xs:element name="section" type="xs:string" minOccurs="1"/>
                            <xs:element name="course" type="xs:string" minOccurs="1"/>
                            <xs:element name="specialization" type="xs:string" minOccurs="1"/>
                            <xs:element name="id" type="xs:integer" minOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="info">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="skills" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="li" maxOccurs="unbounded"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="p_language" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="li" maxOccurs="unbounded"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="tools" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="li" maxOccurs="unbounded"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="education" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="elementary" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="school" type="xs:string"/>
                                        <xs:element name="year" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="junior_high" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="school" type="xs:string"/>
                                        <xs:element name="year" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="senior_high" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="school" type="xs:string"/>
                                        <xs:element name="course" type="xs:string"/>
                                        <xs:element name="year" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="college" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="school" type="xs:string"/>
                                        <xs:element name="course" type="xs:string"/>
                                        <xs:element name="year" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>